name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Deploy Site
        run: curl -X POST -d {} ${{secrets.NETLIFY_BUILD_HOOKS}}
